hpmsb/config/routes.rb
Hpmsb::Application.routes.draw do
  resources :post_categories

  resources :division_categories

  resources :members

  devise_for :member_users
  resources :achievements
  resources :journals
  resources :alumnis
  resources :galleries
  resources :abouts
  resources :histories 
  resources :agendas
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  resources :profiles
  resources :divisions 
  resources :galleries 
  resources :divisions
  resources :inventories  
  resources :elder_members  
  resources :guests   
  resources :static_pages
  resources :posts do
    resources :comments
  end
  root to: "posts#index"
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',  to: 'static_pages#about',    via: 'get'

end

hpmsb/app/models/about.rb
class About < ActiveRecord::Base
end

hpmsb/app/models/achievement.rb
class Achievement < ActiveRecord::Base
end

hpmsb/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

hpmsb/app/models/agenda.rb
class Agenda < ActiveRecord::Base
	validates :agenda_id, presence: true, length: {maximum: 60}
	validates :date, presence: true
	validates :event, presence: true
	validates :venue, presence: true
end

hpmsb/app/models/alumni.rb
class Alumni < ActiveRecord::Base
has_attached_file :avatar, 
:path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
:url => "/system/:attachment/:id/:basename_:style.:extension",
:styles => {
  :thumb    => ['100x100#',  :jpg, :quality => 70],
  :preview  => ['480x480#',  :jpg, :quality => 70],
  :large    => ['600>',      :jpg, :quality => 70],
  :retina   => ['1200>',     :jpg, :quality => 30]
},
:convert_options => {
  :thumb    => '-set colorspace sRGB -strip',
  :preview  => '-set colorspace sRGB -strip',
  :large    => '-set colorspace sRGB -strip',
  :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
}

validates_attachment :avatar,
    :presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

hpmsb/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

hpmsb/app/models/division.rb
class Division < ActiveRecord::Base
 	validates :division_id, presence: true
  	validates :program, presence: true
  	validates :start_date, presence: true
  	validates :end_date, presence: true
  	validates :cost, presence: true
  	validates :status, presence: true
end

hpmsb/app/models/elder_member.rb
class ElderMember < ActiveRecord::Base

end

hpmsb/app/models/gallery.rb
class Gallery < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

hpmsb/app/models/guest.rb
class Guest < ActiveRecord::Base
	validates :guest_id, presence: true
	validates :full_name, presence: true
	validates :address, presence: true
	validates :cek_in, presence: true
	validates :cek_out, presence: true
	validates :necessary, presence: true
	validates :price, presence: true
end

hpmsb/app/models/history.rb
class History < ActiveRecord::Base
	validates :title, presence: true
	validates :history, presence: true
end

hpmsb/app/models/inventory.rb
class Inventory < ActiveRecord::Base
	validates :inventory_id, presence: true
	validates :name, presence: true
	validates :number, presence: true
	validates :status, presence: true
end

hpmsb/app/models/journal.rb
class Journal < ActiveRecord::Base
end

hpmsb/app/models/member.rb
class Member < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

hpmsb/app/models/member_user.rb
class MemberUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

hpmsb/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true, length: {maximum: 60}
	validates :body, presence: true
end

hpmsb/app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :Post
end

hpmsb/app/models/profile.rb
class Profile < ActiveRecord::Base
  validates :profile_id, presence: true
  validates :title, presence: true
  validates :address, presence: true
  validates :vision, presence: true
  validates :mission, presence: true
end

hpmsb/app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

hpmsb/app/controllers/post_categories_controller.rb
class PostCategoriesController < ApplicationController
  before_action :set_post_category, only: [:show, :edit, :update, :destroy]

  # GET /post_categories
  # GET /post_categories.json
  def index
    @post_categories = PostCategory.all
  end

  # GET /post_categories/1
  # GET /post_categories/1.json
  def show
  end

  # GET /post_categories/new
  def new
    @post_category = PostCategory.new
  end

  # GET /post_categories/1/edit
  def edit
  end

  # POST /post_categories
  # POST /post_categories.json
  def create
    @post_category = PostCategory.new(post_category_params)

    respond_to do |format|
      if @post_category.save
        format.html { redirect_to @post_category, notice: 'Post category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @post_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_categories/1
  # PATCH/PUT /post_categories/1.json
  def update
    respond_to do |format|
      if @post_category.update(post_category_params)
        format.html { redirect_to @post_category, notice: 'Post category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_categories/1
  # DELETE /post_categories/1.json
  def destroy
    @post_category.destroy
    respond_to do |format|
      format.html { redirect_to post_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_category
      @post_category = PostCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_category_params
      params.require(:post_category).permit(:name, :description, :Post_id)
    end
end

hpmsb/app/helpers/abouts_helper.rb
module AboutsHelper
end

hpmsb/app/helpers/post_categories_helper.rb
module PostCategoriesHelper
end

hpmsb/app/helpers/posts_helper.rb
module PostsHelper
end

hpmsb/app/views/post_categories/_form.html.erb
<%= form_for(@post_category) do |f| %>
  <% if @post_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_category.errors.count, "error") %> prohibited this post_category from being saved:</h2>

      <ul>
      <% @post_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :Post_id %><br>
    <%= f.text_field :Post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hpmsb/app/views/post_categories/edit.html.erb
<h1>Editing post_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_category %> |
<%= link_to 'Back', post_categories_path %>

hpmsb/app/views/post_categories/index.html.erb
<h1>Listing post_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Post</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @post_categories.each do |post_category| %>
      <tr>
        <td><%= post_category.name %></td>
        <td><%= post_category.description %></td>
        <td><%= post_category.Post %></td>
        <td><%= link_to 'Show', post_category %></td>
        <td><%= link_to 'Edit', edit_post_category_path(post_category) %></td>
        <td><%= link_to 'Destroy', post_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post category', new_post_category_path %>

hpmsb/app/views/post_categories/new.html.erb
<h1>New post_category</h1>

<%= render 'form' %>

<%= link_to 'Back', post_categories_path %>

hpmsb/app/views/post_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post_category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post_category.description %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_category.Post %>
</p>

<%= link_to 'Edit', edit_post_category_path(@post_category) %> |
<%= link_to 'Back', post_categories_path %>