hpmsb/config/routes.rb
Hpmsb::Application.routes.draw do
  resources :post_categories

  resources :division_categories

  resources :members

  devise_for :member_users
  resources :achievements
  resources :journals
  resources :alumnis
  resources :galleries
  resources :abouts
  resources :histories 
  resources :agendas
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  resources :profiles
  resources :divisions 
  resources :galleries 
  resources :divisions
  resources :inventories  
  resources :elder_members  
  resources :guests   
  resources :static_pages
  resources :posts do
    resources :comments
  end
  root to: "posts#index"
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',  to: 'static_pages#about',    via: 'get'

end

hpmsb/app/models/about.rb
class About < ActiveRecord::Base
end

hpmsb/app/models/achievement.rb
class Achievement < ActiveRecord::Base
end

hpmsb/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

hpmsb/app/models/agenda.rb
class Agenda < ActiveRecord::Base
	validates :agenda_id, presence: true, length: {maximum: 60}
	validates :date, presence: true
	validates :event, presence: true
	validates :venue, presence: true
end

hpmsb/app/models/alumni.rb
class Alumni < ActiveRecord::Base
has_attached_file :avatar, 
:path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
:url => "/system/:attachment/:id/:basename_:style.:extension",
:styles => {
  :thumb    => ['100x100#',  :jpg, :quality => 70],
  :preview  => ['480x480#',  :jpg, :quality => 70],
  :large    => ['600>',      :jpg, :quality => 70],
  :retina   => ['1200>',     :jpg, :quality => 30]
},
:convert_options => {
  :thumb    => '-set colorspace sRGB -strip',
  :preview  => '-set colorspace sRGB -strip',
  :large    => '-set colorspace sRGB -strip',
  :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
}

validates_attachment :avatar,
    :presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

hpmsb/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

hpmsb/app/models/division.rb
class Division < ActiveRecord::Base
 	validates :division_id, presence: true
  	validates :program, presence: true
  	validates :start_date, presence: true
  	validates :end_date, presence: true
  	validates :cost, presence: true
  	validates :status, presence: true
end

hpmsb/app/models/elder_member.rb
class ElderMember < ActiveRecord::Base

end

hpmsb/app/models/gallery.rb
class Gallery < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

hpmsb/app/models/guest.rb
class Guest < ActiveRecord::Base
	validates :guest_id, presence: true
	validates :full_name, presence: true
	validates :address, presence: true
	validates :cek_in, presence: true
	validates :cek_out, presence: true
	validates :necessary, presence: true
	validates :price, presence: true
end

hpmsb/app/models/history.rb
class History < ActiveRecord::Base
	validates :title, presence: true
	validates :history, presence: true
end

hpmsb/app/models/inventory.rb
class Inventory < ActiveRecord::Base
	validates :inventory_id, presence: true
	validates :name, presence: true
	validates :number, presence: true
	validates :status, presence: true
end

hpmsb/app/models/journal.rb
class Journal < ActiveRecord::Base
end

hpmsb/app/models/member.rb
class Member < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

hpmsb/app/models/member_user.rb
class MemberUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

hpmsb/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true, length: {maximum: 60}
	validates :body, presence: true
end

hpmsb/app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :Post
end

hpmsb/app/models/profile.rb
class Profile < ActiveRecord::Base
  validates :profile_id, presence: true
  validates :title, presence: true
  validates :address, presence: true
  validates :vision, presence: true
  validates :mission, presence: true
end

hpmsb/app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

hpmsb/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show

  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render action: 'show', status: :created, location: @member }
      else
        format.html { render action: 'new' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:member_id, :full_name, :place_of_birth, :birthday, :ksb_address, :sub_district, :jogja_address, :gender, :phone, :pin_bb, :college, :major, :avatar)
    end
end

hpmsb/app/helpers/abouts_helper.rb
module AboutsHelper
end

hpmsb/app/helpers/members_helper.rb
module MembersHelper
end

hpmsb/app/helpers/posts_helper.rb
module PostsHelper
end

hpmsb/app/views/members/_form.html.erb
<%= form_for @member, html: { multipart: true } do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br>
    <%= f.text_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :place_of_birth %><br>
    <%= f.text_field :place_of_birth %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :ksb_address %><br>
    <%= f.text_area :ksb_address %>
  </div>
  <div class="field">
    <%= f.label :sub_district %><br>
    <%= f.text_field :sub_district %>
  </div>
  <div class="field">
    <%= f.label :jogja_address %><br>
    <%= f.text_area :jogja_address %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :pin_bb %><br>
    <%= f.text_field :pin_bb %>
  </div>
  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div class="field">
    <%= f.label :major %><br>
    <%= f.text_field :major %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hpmsb/app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

hpmsb/app/views/members/index.html.erb
<button class="btn btn-large btn-success btn-block"><i class="icon-th-list icon-white"></i>Anggota</button>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Member</th>
      <th>Full name</th>
      <th>Place of birth</th>
      <th>Birthday</th>
      <th>Ksb address</th>
      <th>Sub district</th>
      <th>Jogja address</th>
      <th>Gender</th>
      <th>Phone</th>
      <th>Pin bb</th>
      <th>College</th>
      <th>Major</th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.member_id %></td>
        <td><%= link_to member.full_name, member %></td>
        <td><%= member.place_of_birth %></td>
        <td><%= member.birthday %></td>
        <td><%= member.ksb_address %></td>
        <td><%= member.sub_district %></td>
        <td><%= member.jogja_address %></td>
        <td><%= member.gender %></td>
        <td><%= member.phone %></td>
        <td><%= member.pin_bb %></td>
        <td><%= member.college %></td>
        <td><%= member.major %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

hpmsb/app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

hpmsb/app/views/members/show.html.erb
<p id="notice"><%= notice %></p>
<button class="btn btn-large btn-success btn-block"><i class="icon-th-list icon-white"></i> Detail Profile Anggota</button>
<table class="table table-bordered">
  <tr>
    <td><img src="<%= image_url @member.avatar_url(:thumb) %>"></td>
  <tr>
    <td><strong>Member:</strong></td>
    <td><%= @member.member_id %></td>
  </tr>
    <td><strong>Full name:</strong></td>
    <td><%= @member.full_name %></td>
  </tr>
    <td><strong>Place of birth:</strong></td>
    <td><%= @member.place_of_birth %></td>
  </tr>
    <td><strong>Birthday:</strong></td>
    <td><%= @member.birthday %></td>
  </tr>
    <td><strong>Ksb address:</strong></td>
    <td><%= @member.ksb_address %></td>
  </tr>
    <td><strong>Sub district:</strong></td>
    <td><%= @member.sub_district %></td>
  </tr>
    <td><strong>Jogja address:</strong></td>
    <td><%= @member.jogja_address %></td>
  </tr>
    <td><strong>Gender:</strong></td>
    <td><%= @member.gender %></td>
  </tr>
    <td><strong>Phone:</strong></td>
    <td><%= @member.phone %></td>
  </tr>
    <td><strong>Pin bb:</strong></td>
    <td><%= @member.pin_bb %></td>
  </tr>
    <td><strong>College:</strong></td>
    <td><%= @member.college %></td>
  </tr>
    <td><strong>Major:</strong></td>
    <td><%= @member.major %></td>

</table>