hpmsb/config/routes.rb
Hpmsb::Application.routes.draw do
  resources :post_categories

  resources :division_categories

  resources :members

  devise_for :member_users
  resources :achievements
  resources :journals
  resources :alumnis
  resources :galleries
  resources :abouts
  resources :histories 
  resources :agendas
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  resources :profiles
  resources :divisions 
  resources :galleries 
  resources :divisions
  resources :inventories  
  resources :elder_members  
  resources :guests   
  resources :static_pages
  resources :posts do
    resources :comments
  end
  root to: "posts#index"
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',  to: 'static_pages#about',    via: 'get'

end

hpmsb/app/models/about.rb
class About < ActiveRecord::Base
end

hpmsb/app/models/achievement.rb
class Achievement < ActiveRecord::Base
end

hpmsb/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

hpmsb/app/models/agenda.rb
class Agenda < ActiveRecord::Base
	validates :agenda_id, presence: true, length: {maximum: 60}
	validates :date, presence: true
	validates :event, presence: true
	validates :venue, presence: true
end

hpmsb/app/models/alumni.rb
class Alumni < ActiveRecord::Base
has_attached_file :avatar, 
:path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
:url => "/system/:attachment/:id/:basename_:style.:extension",
:styles => {
  :thumb    => ['100x100#',  :jpg, :quality => 70],
  :preview  => ['480x480#',  :jpg, :quality => 70],
  :large    => ['600>',      :jpg, :quality => 70],
  :retina   => ['1200>',     :jpg, :quality => 30]
},
:convert_options => {
  :thumb    => '-set colorspace sRGB -strip',
  :preview  => '-set colorspace sRGB -strip',
  :large    => '-set colorspace sRGB -strip',
  :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
}

validates_attachment :avatar,
    :presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

hpmsb/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

hpmsb/app/models/division.rb
class Division < ActiveRecord::Base
 	validates :division_id, presence: true
  	validates :program, presence: true
  	validates :start_date, presence: true
  	validates :end_date, presence: true
  	validates :cost, presence: true
  	validates :status, presence: true
end

hpmsb/app/models/elder_member.rb
class ElderMember < ActiveRecord::Base

end

hpmsb/app/models/gallery.rb
class Gallery < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

hpmsb/app/models/guest.rb
class Guest < ActiveRecord::Base
	validates :guest_id, presence: true
	validates :full_name, presence: true
	validates :address, presence: true
	validates :cek_in, presence: true
	validates :cek_out, presence: true
	validates :necessary, presence: true
	validates :price, presence: true
end

hpmsb/app/models/history.rb
class History < ActiveRecord::Base
	validates :title, presence: true
	validates :history, presence: true
end

hpmsb/app/models/inventory.rb
class Inventory < ActiveRecord::Base
	validates :inventory_id, presence: true
	validates :name, presence: true
	validates :number, presence: true
	validates :status, presence: true
end

hpmsb/app/models/journal.rb
class Journal < ActiveRecord::Base
end

hpmsb/app/models/member.rb
class Member < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

hpmsb/app/models/member_user.rb
class MemberUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

hpmsb/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true, length: {maximum: 60}
	validates :body, presence: true
end

hpmsb/app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :Post
end

hpmsb/app/models/profile.rb
class Profile < ActiveRecord::Base
  validates :profile_id, presence: true
  validates :title, presence: true
  validates :address, presence: true
  validates :vision, presence: true
  validates :mission, presence: true
end

hpmsb/app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

hpmsb/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gallery }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:title, :description)
    end
end

hpmsb/app/helpers/abouts_helper.rb
module AboutsHelper
end

hpmsb/app/helpers/galleries_helper.rb
module GalleriesHelper
end

hpmsb/app/helpers/posts_helper.rb
module PostsHelper
end

hpmsb/app/views/galleries/_form.html.erb
<%= form_for @gallery, html: { multipart: true } do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
    <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hpmsb/app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

hpmsb/app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.title %></td>
        <td><%= gallery.description %></td>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

hpmsb/app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

hpmsb/app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gallery.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gallery.description %>
</p>

  <strong>image:</strong>
	<%= image_tag @gallery.image.url(:thumb) %>
	<br>


<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>